module.exports = {
  duplicateEmail: 'Этот электронный адрес уже используется',
  invalidData: 'Предоставлены неверные данные',
  invalidMovieData: 'Переданы некорректные данные при создании фильма.',
  movieNotFound: 'Фильм с указанным _id не найден',
  unauthorizedToDeleteMovie: 'Нет прав для удаления чужого фильма',
  invalidMovieIdData: 'Переданы некорректные данные при удалении фильма',
  movieDeleted: 'Фильм удален',
  userNotFound: 'Пользователь с таким емайлом не существует',
  duplicateEmailConflict: 'Пользователь с таким емайлом уже существует',
  internalServerError: 'На сервере произошла ошибка',
  authorizationRequired: 'Необходима авторизация',
  authorizationError: 'Ошибка авторизации',
  rateLimitErrorMessage: 'Слишком много запросов с этого IP, попробуйте позже.',
  movieNotFoundToDeleteOther: 'Фильм с указанным _id не найден',
  invalidUrl: 'Некорректный url адрес',
  invalidEmailFormat: 'Неверный формат электронной почты',
  wrongCredentials: 'Неправильный адрес электронной почты или пароль',
  pageNotFound: 'Страница по указанному маршруту не найдена',
};
